#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      duckdb_version: v1.0.0
      extension_name: duckdb-bigquery
      exclude_archs: 'linux_amd64_gcc4;linux_arm64;osx_amd64;wasm_mvp;wasm_eh;wasm_threads;windows_amd64;windows_amd64_rtools'

  # duckdb-stable-deploy:
  #   name: Deploy extension binaries
  #   needs: duckdb-stable-build
  #   uses: ./.github/workflows/_extension_deploy.yml
  #   secrets: inherit
  #   with:
  #     duckdb_version: v1.0.0
  #     extension_name: duckdb-bigquery
  #     exclude_archs: 'linux_amd64;linux_amd64_gcc4;linux_arm64;osx_amd64;wasm_mvp;wasm_eh;wasm_threads;windows_amd64;windows_amd64_rtools'
  #     deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
  #     deploy_versioned: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}